### ISSUE TITLE
Problems with ``IplSound.brsar``

### ISSUE THREAD

**Issue by yell0wsuit** [em-eight/mrst#3]
When I tried extracting the ``IplSound.brsar`` (Wii System menu sound and music), I got error on Windows due to invalid file characters.

On Linux it has no problem, but the wave file seems broken (the screenshot is from WSL).

![image](https://github.com/em-eight/mrst/assets/5692900/d4e4b12c-bbe6-4cc8-9c48-7bd2a85851c6)

https://github.com/em-eight/mrst/blob/7160f85009b9ac8626d7983a8898f2665c7a410b/src/tools/extract.cpp#L112

Maybe due to unknown magic?

**Comment by em-eight** [comment]
Hmmm, this tool is supporting every brsar file format so it's probably that this sound either doesn't have wave data (which afaik is never the case with BRWSD files) or the tool incorrectly calculates its location inside the file. I'll try to get my hands on `IplSound.brsar` and investigate.

**Comment by em-eight** [comment]
Apparently the Wii menu uses an old RSAR format where wave data is embedded in RBNK and RWSD files. I can fix it pretty soon.

Opened a separate issue #4

**Comment by yell0wsuit** [comment]
Ok, I will test other Wii channel files too to see if any issues arise.

**Comment by em-eight** [comment]
> Ok, I will test other Wii channel files too to see if any issues arise.
> 
>     * `NigaoeSound.brsar`: same error
> 
>     * `rev_enquete.brsar`: same error
> 
>     * `miiConChSound.brsar`: same error
> 
>     * `prmSound.brsar` (Nintendo Channel): can be extracted, but empty folder

Thanks for testing, I more or less expected that since those BRSARs were created around the same time so they share similar BRSAR versions.

I have published a new release https://github.com/em-eight/mrst/releases/tag/v1.2-rc1
In my tests all samples in `IplSound.brsar` are being extracted correctly, can you give it a try?

Don't forget to decode while extracting the BRSAR. Otherwise you will only get the standalone subfiles.
`mrst extract --decode <brsar>`

The reason is newer BRSARs contained the audio sample in independent files (BRWARs and BRWAVs) so they could be decoded independently after extraction, but in these old BRSARs you need multiple subfiles to decode them (both the BRBNK/BRWSD and the DSP data).

**Comment by yell0wsuit** [comment]
Ok. So I tested with ``IplSound.brsar`` and it partially works.

The problem now is: when I use the ``--decode`` command, the sf2 file located in ``IplSound.brsar.d/GROUP_STATIC/8`` (Wii menu soundfont) is only 5KB. The WAVs inside sf2 are apparently empty, which makes the soundfont blank(?).

Also, in that same folder, is it possible to extract individual WAVs (or better, original file format) that has looping points? VGMStream can embed looping points to WAV file.

**Comment by em-eight** [comment]
> Ok. So I tested with `IplSound.brsar` and it partially works.
> 
> The problem now is: when I use the `--decode` command, the sf2 file located in `IplSound.brsar.d/GROUP_STATIC/8` (Wii menu soundfont) is only 5KB. The WAVs inside sf2 are apparently empty, which makes the soundfont blank(?).
> 
> Also, in that same folder, is it possible to extract individual WAVs (or better, original file format) that has looping points? VGMStream can embed looping points to WAV file.

Ah, I'll need to investigate on that.

Eventually I'll get to a wav export option for banks, but since .sf2 is a mainstream file format you can use common tools like polyphone to extract samples from soundfonts

**Comment by yell0wsuit** [comment]
Oh, the ``prmSound.brsar`` file is still produces 0 files from the tool.

**Comment by em-eight** [comment]
> Ok. So I tested with `IplSound.brsar` and it partially works.
> 
> The problem now is: when I use the `--decode` command, the sf2 file located in `IplSound.brsar.d/GROUP_STATIC/8` (Wii menu soundfont) is only 5KB. The WAVs inside sf2 are apparently empty, which makes the soundfont blank(?).
> 
> Also, in that same folder, is it possible to extract individual WAVs (or better, original file format) that has looping points? VGMStream can embed looping points to WAV file.

Update: latest release should work https://github.com/em-eight/mrst/releases/tag/v1.2-rc%EF%BC%92
Apparently the wii menu BGM is the only audio I've encounted where PCM16 is used. I guess they felt that that relaxing ambience needed to be lossless. The resulting soundfont along with the decoded midi from group 9 creates quite the faithful recreation of that BGM!

PCM16 seems to be so rare that BrawlCrate which has been out there for like 10 years can't parse that bank correctly either. I wonder if VGMTrans works

As for `prmSound.brsar`, I can't find it anywhere to test if the new changes fix it. Can you try it and if it doesn't work, let me know how can I get my hands on it?

Again thanks for the thorough testing. All these obscure ancient BRSARs are pretty good for debugging

**Comment by yell0wsuit** [comment]
Thanks, the Wii soundfont issue has been fixed. It would be nice to have individual WAVs extracted with embedded looping metadata because I want to use them with the rbnk file, and sf2 seems to be limited and a nuisance to work with (sorry for my niche case!)

> PCM16 seems to be so rare that BrawlCrate which has been out there for like 10 years can't parse that bank correctly either. I wonder if VGMTrans works

There are some tools and scripts for extracting the BRSAR format, but most of them are outright broken or refuse to work with certain types of BRSAR. BrawlCrate/BrawlBox is only for, well, Smash Brawl, and its devs don't want to make it as general-purpose BRSAR tool.  
So far, only Jasper's fork of VGMTrans can handle BRSAR well--but it only dumps the raw format. Your tool seems to have potential, so I will continue to test it for you :)

> As for prmSound.brsar, I can't find it anywhere to test if the new changes fix it. Can you try it and if it doesn't work, let me know how can I get my hands on it?

Here is the ``prmSound`` file to save you time: [prmSound.zip](https://github.com/user-attachments/files/15934922/prmSound.zip). I got it from WiiLink24.

**Comment by em-eight** [comment]
> Thanks, the Wii soundfont issue has been fixed. It would be nice to have individual WAVs extracted with embedded looping metadata because I want to use them with the rbnk file, and sf2 seems to be limited and a nuisance to work with (sorry for my niche case!)
> 
> > PCM16 seems to be so rare that BrawlCrate which has been out there for like 10 years can't parse that bank correctly either. I wonder if VGMTrans works
> 
> There are some tools and scripts for extracting the BRSAR format, but most of them are outright broken or refuse to work with certain types of BRSAR. BrawlCrate/BrawlBox is only for, well, Smash Brawl, and its devs don't want to make it as general-purpose BRSAR tool. So far, only Jasper's fork of VGMTrans can handle BRSAR well--but it only dumps the raw format. Your tool seems to have potential, so I will continue to test it for you :)
> 
> > As for prmSound.brsar, I can't find it anywhere to test if the new changes fix it. Can you try it and if it doesn't work, let me know how can I get my hands on it?
> 
> Here is the `prmSound` file to save you time: [prmSound.zip](https://github.com/user-attachments/files/15934922/prmSound.zip). I got it from WiiLink24.

Yea VGMTrans is great, I've borrowed some code from there. I still wanted to create a separate tool because 1) vgmtrans is only for sequenced effects and I want something with all Wii stuff in the same place 2) the fork has been abandoned and it's hard to work with/improve since upstream has diverged 

Yet another release: https://github.com/em-eight/mrst/releases/tag/v1.2-rc3
The brseq in group item 10 has an MML command that is not supported yet, I'll deal with that at some point. It's a bit annoying that MIDI doesn't have any equivalent to some of the MML commands

**Comment by yell0wsuit** [comment]
> It's a bit annoying that MIDI doesn't have any equivalent to some of the MML commands

Yep, this is why I prefer working on the original file format. BSEQ/CSEQ format has more controls and some commands that a MIDI cannot replicate/emulate.

**Comment by em-eight** [comment]
Aight, I will close this then. Thanks again, and let me know if you encounter any new issues!
