### ISSUE TITLE
[Feature request] Ability to match extracted file with "real" name from BRSAR when extracting

### ISSUE THREAD

**Issue by yell0wsuit** [em-eight/mrst#5]
As of now, extracting gives just ``file.brseq``, ``file.brbnk``, etc., which is confusing. So, having actual names makes it easier to differentiate among files.

Since this tool has the ``list`` command that lists the names, I think it's possible to match those with the extracted files.

**Comment by em-eight** [comment]
These subfiles correspond to group entries, which are not given names in BRSAR. `'list` lists the group names, sound names or bank names. Technically I could associate these names with the group entries they reference, but each name could be associated with up to 4 files. Even in the original brsar tool, there is no 1-1 association between individual files and sound/bank/group names, so I decided to keep things straightforward

**Comment by em-eight** [comment]
Closing issue due to no clear association between sounds and BRSAR subfiles
